name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test-package:
    
        runs-on: macos-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Select Xcode
          run: sudo xcode-select -switch /Applications/Xcode_12.3.app
        
        - name: Generate Xcode Project
          run: swift package generate-xcodeproj

        - name: Run Test
          run: xcodebuild clean test -destination 'name=iPhone 11' -scheme 'JSConstraints-Package'
