name: status

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test-package:

        runs-on: macos-latest

        strategy:
          matrix:
            destination: ['platform=iOS Simulator,OS=12.2,name=iPhone X', 'platform=tvOS Simulator,OS=12.2,name=Apple TV 4K']

        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Run Test
          run: xcodebuild clean test -project JSConstraints.xcodeproj -destination ${{ matrix.destination }} -scheme 'JSConstraints-Package'
