name: status

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test-package:

        runs-on: macos-latest

        strategy:
          matrix:
            destination: ['platform:iOS Simulator, OS:15.2, name:iPhone 12', 'platform:tvOS Simulator, OS:15.2, name:Apple TV 4K']

        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Generate Xcode Project
          run: swift package generate-xcodeproj

        - name: Run Test
          run: xcodebuild clean test -project JSConstraints.xcodeproj -destination "${destination}" -scheme 'JSConstraints-Package'
          env:
            destination: ${{ matrix.destination }}
